[package]
name = "chef"
version = "0.1.0"
description = "Chef desktop utility toolbox"
authors = ["czeong"]
license = "MIT"
edition = "2021"
rust-version = "1.75"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
